In [1]:
import torch
import torchvision
import h5py
import numpy as np
import keras
import tensorflow as tf
from main import EfficientNetB0
import efficientnet.tfkeras as efn
from keras import layers
from torch import nn
from torchvision import transforms
from keras.applications import imagenet_utils

In [2]:
import tensorflow.python.ops.numpy_ops.np_config as np_config
np_config.enable_numpy_behavior()

In [3]:
deep_prof_model = tf.keras.models.load_model('model', compile=False)

In [4]:
for i,l in enumerate(deep_prof_model.layers):
    if l.get_weights():
        print(i, l.get_config()['name'], l.get_weights()[0].shape)
        print(len(l.get_weights()))
        try:
            print(l.get_weights()[1].shape)
        except:
            continue

1 stem_conv (3, 3, 5, 32)
1
2 stem_bn (32,)
4
(32,)
4 block1a_dwconv (3, 3, 32, 1)
1
5 block1a_bn (32,)
4
(32,)
9 block1a_se_reduce (1, 1, 32, 8)
2
(8,)
10 block1a_se_expand (1, 1, 8, 32)
2
(32,)
12 block1a_project_conv (1, 1, 32, 16)
1
13 block1a_project_bn (16,)
4
(16,)
14 block2a_expand_conv (1, 1, 16, 96)
1
15 block2a_expand_bn (96,)
4
(96,)
17 block2a_dwconv (3, 3, 96, 1)
1
18 block2a_bn (96,)
4
(96,)
22 block2a_se_reduce (1, 1, 96, 4)
2
(4,)
23 block2a_se_expand (1, 1, 4, 96)
2
(96,)
25 block2a_project_conv (1, 1, 96, 24)
1
26 block2a_project_bn (24,)
4
(24,)
27 block2b_expand_conv (1, 1, 24, 144)
1
28 block2b_expand_bn (144,)
4
(144,)
30 block2b_dwconv (3, 3, 144, 1)
1
31 block2b_bn (144,)
4
(144,)
35 block2b_se_reduce (1, 1, 144, 6)
2
(6,)
36 block2b_se_expand (1, 1, 6, 144)
2
(144,)
38 block2b_project_conv (1, 1, 144, 24)
1
39 block2b_project_bn (24,)
4
(24,)
42 block3a_expand_conv (1, 1, 24, 144)
1
43 block3a_expand_bn (144,)
4
(144,)
45 block3a_dwconv (5, 5, 144, 1)
1
46 blo

In [5]:
model = efn.EfficientNetB0(weights='imagenet')

In [6]:
for i,l in enumerate(model.layers):
    if l.get_weights():
        print(i, l.get_config()['name'], l.get_weights()[0].shape)
        try:
            print(l.get_weights()[1].shape)
        except:
            continue

1 stem_conv (3, 3, 3, 32)
2 stem_bn (32,)
(32,)
4 block1a_dwconv (3, 3, 32, 1)
5 block1a_bn (32,)
(32,)
9 block1a_se_reduce (1, 1, 32, 8)
(8,)
10 block1a_se_expand (1, 1, 8, 32)
(32,)
12 block1a_project_conv (1, 1, 32, 16)
13 block1a_project_bn (16,)
(16,)
14 block2a_expand_conv (1, 1, 16, 96)
15 block2a_expand_bn (96,)
(96,)
17 block2a_dwconv (3, 3, 96, 1)
18 block2a_bn (96,)
(96,)
22 block2a_se_reduce (1, 1, 96, 4)
(4,)
23 block2a_se_expand (1, 1, 4, 96)
(96,)
25 block2a_project_conv (1, 1, 96, 24)
26 block2a_project_bn (24,)
(24,)
27 block2b_expand_conv (1, 1, 24, 144)
28 block2b_expand_bn (144,)
(144,)
30 block2b_dwconv (3, 3, 144, 1)
31 block2b_bn (144,)
(144,)
35 block2b_se_reduce (1, 1, 144, 6)
(6,)
36 block2b_se_expand (1, 1, 6, 144)
(144,)
38 block2b_project_conv (1, 1, 144, 24)
39 block2b_project_bn (24,)
(24,)
42 block3a_expand_conv (1, 1, 24, 144)
43 block3a_expand_bn (144,)
(144,)
45 block3a_dwconv (5, 5, 144, 1)
46 block3a_bn (144,)
(144,)
50 block3a_se_reduce (1, 1, 144,

In [7]:
effnet = EfficientNetB0(input_shape=[1, 3, 224, 224], num_channels=3)
effnet1 = EfficientNetB0(input_shape=[1, 3, 224, 224],num_channels=3)

In [8]:
for k,v in effnet.state_dict().items():
    print(k,v.shape)

conv1.weight torch.Size([32, 3, 3, 3])
batch_norm1.weight torch.Size([32])
batch_norm1.bias torch.Size([32])
batch_norm1.running_mean torch.Size([32])
batch_norm1.running_var torch.Size([32])
batch_norm1.num_batches_tracked torch.Size([])
block_list.0.depth_conv.weight torch.Size([32, 1, 3, 3])
block_list.0.batch_norm_depth.weight torch.Size([32])
block_list.0.batch_norm_depth.bias torch.Size([32])
block_list.0.batch_norm_depth.running_mean torch.Size([32])
block_list.0.batch_norm_depth.running_var torch.Size([32])
block_list.0.batch_norm_depth.num_batches_tracked torch.Size([])
block_list.0.conv_se_reduce.weight torch.Size([8, 32, 1, 1])
block_list.0.conv_se_reduce.bias torch.Size([8])
block_list.0.conv_se_expand.weight torch.Size([32, 8, 1, 1])
block_list.0.conv_se_expand.bias torch.Size([32])
block_list.0.conv_output.weight torch.Size([16, 32, 1, 1])
block_list.0.batch_norm_last.weight torch.Size([16])
block_list.0.batch_norm_last.bias torch.Size([16])
block_list.0.batch_norm_last.r

In [63]:
# initialize the state dictionary from the pytorch model to be editted
sd = effnet.state_dict()

In [64]:
keras_pytorch_convert = {'se_reduce':'conv_se_reduce','se_expand':'conv_se_expand','project_conv':'conv_output',
                       'expand_conv':'conv_expand', 'dwconv':'depth_conv','top_conv':'conv_final','probs':'linear',
                      'stem_conv':'conv1', 'stem_bn':'batch_norm1', 'top_bn':'batch_norm_final','expand_bn':'batch_norm_exp',
                        'bn':'batch_norm_depth','project_bn':'batch_norm_last'}

In [65]:
# doesnt work on depth conv
# transpose works on everything else

In [66]:
layer = -1
name = ''
for i,l in enumerate(model.layers):
    if l.get_weights():
        org_name = l.get_config()['name']
        weights = l.get_weights()
        # any weights in a block unit
        if org_name[0:5] == 'block':
            if org_name[5:7] != name:
                layer += 1
                name=org_name[5:7]
            base_pyt = 'block_list.'
            print('======'*7)
            print('keras')
            print('pytorch')
            print(org_name)
            if keras_pytorch_convert.get(org_name[8:]):
                use = keras_pytorch_convert[org_name[8:]]
                py_name = f'{base_pyt}{layer}.{use}'
                if org_name[8:] == 'dwconv':
                    new_weights = torch.from_numpy(weights[0]).permute(2,3,0,1)
                    sd[py_name+'.weight'] = new_weights
                # any non batchnorm or non depthconv layer
                elif 'bn' not in org_name:
                    new_weights = weights[0]
                    if 'conv' in org_name:
                        new_weights = torch.from_numpy(np.moveaxis(new_weights, [-1, -2], [0, 1]))
                    else:
                        new_weights = torch.from_numpy(new_weights.T)
                    sd[py_name+'.weight'] = new_weights
                    # this means theres a bias to account for
                    if len(weights)>1:
                        new_weights = weights[1]
                        new_weights = torch.from_numpy(new_weights)
                        sd[py_name+'.bias'] = new_weights
                # its a batchnorm layer
                else:
                    new_weights = weights[0]
                    new_weights = torch.from_numpy(new_weights)
                    sd[py_name+'.weight'] = new_weights
                    # this means theres a bias to account for
                    if len(weights)>1:
                        new_weights = [torch.from_numpy(i) for i in weights]
                        sd[py_name+'.bias'] = new_weights[1]
                        sd[py_name+'.running_mean'] = new_weights[2]
                        sd[py_name+'.running_var'] = new_weights[3]
            else:
                continue
        # initial convs or final convs
        else:
            print('======'*7)
            print(org_name)
            py_name = keras_pytorch_convert[org_name]
            if 'bn' in org_name:
                new_weights = torch.from_numpy(weights[0])
            else:
                new_weights = torch.from_numpy(np.moveaxis(weights[0], [-1, -2], [0, 1]))
            sd[py_name+'.weight'] = new_weights
            # handle bias weights as well
            if len(weights) > 1:
                new_weights = [torch.from_numpy(i) for i in weights]
                sd[py_name+'.bias'] = new_weights[1]
                if org_name == 'probs':
                    continue
                sd[py_name+'.running_mean'] = new_weights[2]
                sd[py_name+'.running_var'] = new_weights[3]

                

stem_conv
stem_bn
keras
pytorch
block1a_dwconv
keras
pytorch
block1a_bn
keras
pytorch
block1a_se_reduce
keras
pytorch
block1a_se_expand
keras
pytorch
block1a_project_conv
keras
pytorch
block1a_project_bn
keras
pytorch
block2a_expand_conv
keras
pytorch
block2a_expand_bn
keras
pytorch
block2a_dwconv
keras
pytorch
block2a_bn
keras
pytorch
block2a_se_reduce
keras
pytorch
block2a_se_expand
keras
pytorch
block2a_project_conv
keras
pytorch
block2a_project_bn
keras
pytorch
block2b_expand_conv
keras
pytorch
block2b_expand_bn
keras
pytorch
block2b_dwconv
keras
pytorch
block2b_bn
keras
pytorch
block2b_se_reduce
keras
pytorch
block2b_se_expand
keras
pytorch
block2b_project_conv
keras
pytorch
block2b_project_bn
keras
pytorch
block3a_expand_conv
keras
pytorch
block3a_expand_bn
keras
pytorch
block3a_dwconv
keras
pytorch
block3a_bn
keras
pytorch
block3a_se_reduce
keras
pytorch
block3a_se_expand
keras
pytorch
block3a_project_conv
keras
pytorch
block3a_project_bn
keras
pytorch
block3b_expand_conv
keras


In [67]:
effnet.load_state_dict(sd)

<All keys matched successfully>

In [70]:
x = np.random.rand(224,224,3)
# x = np.ones((224,224,3))
x = np.array([x])
x_t = torch.from_numpy(x)
x_t = x_t.permute(0,3,1,2).float()
print(x.shape, x_t.shape)

(1, 224, 224, 3) torch.Size([1, 3, 224, 224])


In [71]:
extractor = keras.Model(inputs=model.inputs,
                        outputs={layer.get_config()['name']:layer.output for layer in model.layers})
features = extractor.predict(x)

In [73]:
#pyt version
effnet.eval()
y_t = effnet(x_t)

here


TypeError: conv2d() received an invalid combination of arguments - got (method, Parameter, NoneType, tuple, str, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (method, Parameter, NoneType, tuple, str, tuple, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (method, Parameter, NoneType, tuple, str, tuple, int)


In [74]:
effnet.outputs.keys()

dict_keys(['conv1', 'bn1', 'activation1'])

In [75]:
list(features.keys())[0:20]

['input_1',
 'stem_conv',
 'stem_bn',
 'stem_activation',
 'block1a_dwconv',
 'block1a_bn',
 'block1a_activation',
 'block1a_se_squeeze',
 'block1a_se_reshape',
 'block1a_se_reduce',
 'block1a_se_expand',
 'block1a_se_excite',
 'block1a_project_conv',
 'block1a_project_bn',
 'block2a_expand_conv',
 'block2a_expand_bn',
 'block2a_expand_activation',
 'block2a_dwconv',
 'block2a_bn',
 'block2a_activation']

In [76]:
test_keras = features['stem_conv'][0]
test_keras.shape

(112, 112, 32)

In [77]:
# test_pyt = effnet.block_list[0].outputs['depth_conv'][0].permute(1,2,0)[0,0:5,0:5]
test_pyt = effnet.outputs['conv1'][0]
test_pyt.shape

torch.Size([32, 112, 112])

In [78]:
test_keras[0:5,0:5,1]

array([[ 0.89257056,  0.64466476, -0.07190483,  0.25204936,  2.086779  ],
       [ 1.8468978 , -1.3588157 ,  0.06381522,  1.1926026 , -0.07757401],
       [-1.2698512 ,  0.8172054 , -0.16187674, -0.49342743, -0.05741452],
       [ 0.6794041 , -3.6215224 , -0.03492995,  1.2019897 , -1.0170628 ],
       [ 0.3571217 , -0.31503797,  0.28771666,  0.64856356,  0.06055938]],
      dtype=float32)

In [79]:
test_pyt.permute(1,2,0)[0:5,0:5,1]

tensor([[ 0.0035,  0.0025, -0.0003,  0.0010,  0.0082],
        [ 0.0072, -0.0053,  0.0003,  0.0047, -0.0003],
        [-0.0050,  0.0032, -0.0006, -0.0019, -0.0002],
        [ 0.0027, -0.0142, -0.0001,  0.0047, -0.0040],
        [ 0.0014, -0.0012,  0.0011,  0.0025,  0.0002]],
       grad_fn=<SelectBackward0>)

In [ ]:
x1[0:5,0:5,1], x_t1.permute(1,2,0)[0:5,0:5,1],

In [9]:
# (top, bottom) (left, right)
imagenet_utils.correct_pad(x,3), correct_pad([1, 3, 224, 224],3)

(((0, 1), (0, 1)), (0, 1, 0, 1))

In [33]:
def correct_pad(input_shape, kernel_size):
    """Returns a tuple for zero-padding for 2D convolution with downsampling.
    Args:
      input_shape: Input img shape
      kernel_size: An integer or tuple/list of 2 integers.
    Returns:
      A tuple.
    """
    img_dim = 2
    input_size = list(input_shape)[img_dim: (img_dim + 2)]
    # 128, 128
    if type(kernel_size):
        kernel_size = (kernel_size, kernel_size)
    # 3, 3
    if input_size[0] is None:
        adjust = (1, 1)
    else:
        adjust = (1 - input_size[0] % 2, 1 - input_size[1] % 2)
    correct = (kernel_size[0] // 2, kernel_size[1] // 2)
    return (
        correct[1] - adjust[1], correct[1],
        correct[0] - adjust[0], correct[0],
    )

In [49]:
x = np.random.rand(224,224,3)
# x = np.ones((224,224,3))
x = np.array([x])
x_t = torch.from_numpy(x)
x_t = x_t.permute(0,3,1,2).float()
print(x.shape, x_t.shape)

(1, 224, 224, 3) torch.Size([1, 3, 224, 224])


In [50]:
x1 = layers.Rescaling(1.0 / 255.0)(x)
x1 = layers.Normalization(axis=1)(x1)
a,b,c,d = correct_pad(x1.shape, 3)
# (top, bottom) (left, right) for padding argument
x1 = layers.ZeroPadding2D(
        padding=imagenet_utils.correct_pad(x,3), data_format='channels_last',name="stem_conv_pad")(x1)

In [51]:
rescale = lambda x: x * 1./255
pyt_transforms = transforms.Compose([
            transforms.Lambda(rescale),
            transforms.Normalize(0, 1),
            # padding left, right, top, bottom
            transforms.Lambda(nn.ZeroPad2d(padding=correct_pad([1, 3, 224, 224],3))),]
        )

In [52]:
x_t1 = pyt_transforms(x_t)

In [53]:
x1.shape, x_t1.shape

(TensorShape([1, 225, 225, 3]), torch.Size([1, 3, 225, 225]))

In [54]:
x1[0][0:3,0:3,0], x_t1[0].permute(1,2,0)[0:3,0:3,0],

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.00390635, 0.00348694, 0.00117885],
        [0.00331971, 0.00014537, 0.00239421],
        [0.00261566, 0.00023715, 0.00024944]], dtype=float32)>,
 tensor([[0.0039, 0.0035, 0.0012],
         [0.0033, 0.0001, 0.0024],
         [0.0026, 0.0002, 0.0002]]))

In [55]:
weights = model.layers[1].get_weights()[0]
print('keras weights: ',weights.shape)
keras_conv = layers.Conv2D(32, 3, strides=2, padding="valid", use_bias=False, weights=np.array([weights]),data_format="channels_last")
pyt_conv = nn.Conv2d(3, 32, kernel_size=3, stride=2, padding="valid", bias=False)
sd = pyt_conv.state_dict()
weights_t = torch.from_numpy(np.moveaxis(weights, [-1, -2], [0, 1]))
# weights_t = torch.from_numpy(weights.T)
print('torch weights: ',weights_t.shape)
sd['weight']= weights_t 
pyt_conv.load_state_dict(sd)

keras weights:  (3, 3, 3, 32)
torch weights:  torch.Size([32, 3, 3, 3])


<All keys matched successfully>

In [56]:
x1 = keras_conv(x1)[0]
x_t1 = pyt_conv(x_t1)[0]

In [57]:
x1.shape, x_t1.shape

(TensorShape([112, 112, 32]), torch.Size([32, 112, 112]))

In [58]:
x1[0:5,0:5,1], x_t1.permute(1,2,0)[0:5,0:5,1],

(<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[ 5.5416930e-03, -7.9710241e-03, -2.9920922e-03,  4.8286426e-03,
         -5.8296393e-03],
        [ 1.5536631e-03, -6.1574881e-03, -2.5852348e-03, -4.3254676e-03,
         -5.1139481e-04],
        [-1.7202171e-03, -2.9728068e-03, -4.9127722e-03, -3.0871422e-05,
          2.7573048e-03],
        [-6.9631397e-04,  1.1423291e-03,  8.1694190e-05, -1.0351182e-03,
          6.3428539e-04],
        [ 2.2146062e-03,  4.2086621e-03,  3.3108596e-04, -4.8314990e-03,
          3.0117733e-03]], dtype=float32)>,
 tensor([[ 5.5417e-03, -7.9710e-03, -2.9921e-03,  4.8286e-03, -5.8296e-03],
         [ 1.5537e-03, -6.1575e-03, -2.5852e-03, -4.3255e-03, -5.1140e-04],
         [-1.7202e-03, -2.9728e-03, -4.9128e-03, -3.0871e-05,  2.7573e-03],
         [-6.9631e-04,  1.1423e-03,  8.1694e-05, -1.0351e-03,  6.3429e-04],
         [ 2.2146e-03,  4.2087e-03,  3.3109e-04, -4.8315e-03,  3.0118e-03]],
        grad_fn=<SelectBackward0>))